### ISSUE TITLE
Get Earnings Calander failing on multiple versions

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#16]
```powershell
https://finance.yahoo.com/calendar/earnings?day=2021-09-26&size=100&offset=0
Traceback (most recent call last):
  File "tasks_to_run.py", line 126, in <module>
    get_earnings_calendar.insert_earnings_into_db(get_earnings_calendar.get_earnings(7, forward=True))
  File "/root/_production_website/AuroraLight/Stocksera/scheduled_tasks/get_earnings_calendar.py", line 70, in get_earnings
    name = tds[1].text
IndexError: list index out of range
```

This error I cannot get past, I have experienced it for multiple versions and have been able to conclude that the link is not broken. All I can gather is that possible the BS4 dom is broken in reference to scraping the data? I have not looked very deep into this one.

**Comment by spartan737** [comment]
I'm not sure why are you facing this error. I just tried it and there's nothing wrong with it.

<img width="552" alt="earnings_git" src="https://user-images.githubusercontent.com/76832850/134923963-3ba7c95a-d4e7-4c98-b402-9c1b3e2c2927.PNG">

**Comment by CodeInFilth** [comment]
> I'm not sure why are you facing this error. I just tried it and there's nothing wrong with it.
> 
> <img alt="earnings_git" width="552" src="https://user-images.githubusercontent.com/76832850/134923963-3ba7c95a-d4e7-4c98-b402-9c1b3e2c2927.PNG">

Strange, I will dig through this error and post the fix today thanks.

Can I ask where the scripts/information on your real time reddit scraping? Will that come soon or are you not sure?

I would really like to see how that works.


P.S. Twitter never wants to approve my developer API so I am working on a twitter scraper without dev information to fill that spot.

**Comment by CodeInFilth** [comment]
> I'm not sure why are you facing this error. I just tried it and there's nothing wrong with it.
> 
> <img alt="earnings_git" width="552" src="https://user-images.githubusercontent.com/76832850/134923963-3ba7c95a-d4e7-4c98-b402-9c1b3e2c2927.PNG">

I found out what the issue is.

```powershell
[<td><img alt="Yahoo Logo" src="https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_205x58_frontpage.png"/><h1 style="margin-top:20px">Will be right back...</h1><p id="message-1">Thank you for your patience.</p><p id="message-2">Our engineers are working quickly to resolve the issue.</p></td>]
```

It seems whenever I request this from yahoo they want to block me or throw an error so I will probably work on a fix today, ill be sure to update you.

**Comment by spartan737** [comment]
I have a sample at https://stocksera.pythonanywhere.com/sample_email/ . Do subscribe at https://stocksera.pythonanywhere.com/subscribe/ if you wish to receive daily updates. The reason why I'm leaving that part out in Github is because theres email addresses of other people in the database, so as a security measure, I do not wish to share any part of the code related to the subscription database.

**Comment by CodeInFilth** [comment]
> I have a sample at [stocksera.pythonanywhere.com/sample_email](https://stocksera.pythonanywhere.com/sample_email/) . Do subscribe at [stocksera.pythonanywhere.com/subscribe](https://stocksera.pythonanywhere.com/subscribe/) if you wish to receive daily updates. The reason why I'm leaving that part out in Github is because theres email addresses of other people in the database, so as a security measure, I do not wish to share any part of the code related to the subscription database.

I would never expect you to actually upload your database of official emails of curious users but would it be possible to include the scripts your using to compose the email format and send it?

I will in that case make a push notification tool replacement.

Thanks!

I didnt get around to the get_earnings_calander.py yet, but ive tested on 3 devices 2 Mac OS and 1 Ubuntu 18.04. About to do some more fixes.
