### ISSUE TITLE
Fresh Pull isnt working with subreddits

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#18]
```bash
earching for tickers in shortsqueeze...
Populating results for shortsqueeze...
Traceback (most recent call last):
  File "tasks_to_run.py", line 94, in <module>
    scrape_reddit_stocks.main()
  File "/root/3_aurora----Production/Stocksera/scheduled_tasks/reddit/stocks/scrape_trending_posts.py", line 25, in main
    results_df = get_financial_stats(results_df, minimum_volume[index], minimum_mkt_cap[index], allow_threading)
  File "/root/3_aurora----Production/Stocksera/scheduled_tasks/reddit/stocks/AutoDD.py", line 258, in get_financial_stats
    quick_stats_df = get_quick_stats(ticker_list, min_vol, min_mkt_cap, threads)
  File "/root/3_aurora----Production/Stocksera/scheduled_tasks/reddit/stocks/AutoDD.py", line 278, in get_quick_stats
    unprocessed_df = download_quick_stats(ticker_list, quick_stats, threads)
  File "/root/3_aurora----Production/Stocksera/scheduled_tasks/reddit/stocks/fast_yahoo.py", line 118, in download_quick_stats
    for retrieved_stats_dict in response_list:
TypeError: 'NoneType' object is not iterable
```

I cannot solve this error and strangly all I need to do is remove the subreddit section of the reddit scrape.

**Comment by CodeInFilth** [comment]
you have corrected the issue if anyone who fetches this uses docker.
