### ISSUE TITLE
FTD Encoding fix

### ISSUE THREAD

**Issue by CodeInFilth** [spartan737/Stocksera#19]
```
https://www.sec.gov/files/data/fails-deliver-data/cnsfails202110a.zip
Traceback (most recent call last):
  File "scheduled_tasks/get_failure_to_deliver.py", line 122, in <module>
    main()
  File "scheduled_tasks/get_failure_to_deliver.py", line 115, in main
    download_ftd()
  File "scheduled_tasks/get_failure_to_deliver.py", line 28, in download_ftd
    df = pd.read_csv(base_url + url_link["href"], delimiter="|", error_bad_lines=False)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 107841: invalid start byte
```

Found a FTD encoding fixture to this error if anyone is experiencing 

nano scheduled_tasks/get_failure_to_deliver.py

on line 28

```
df = pd.read_csv(base_url + url_link["href"], delimiter="|", error_bad_lines=False)
```
into this
```
df = pd.read_csv(base_url + url_link["href"], delimiter="|",encoding='latin1', error_bad_lines=False)
```

**Comment by spartan737** [comment]
encoding="cp1252" works as well. Changes committed to Github
